saleor/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.views import serve
from django.urls import re_path
from django.views.decorators.csrf import csrf_exempt

from .core.views import jwks
from .graphql.api import backend, schema
from .graphql.views import GraphQLView
from .plugins.views import (
    handle_global_plugin_webhook,
    handle_plugin_per_channel_webhook,
    handle_plugin_webhook,
)
from .product.views import digital_product
from .thumbnail.views import handle_thumbnail

urlpatterns = [
    re_path(
        r"^graphql/$",
        csrf_exempt(GraphQLView.as_view(backend=backend, schema=schema)),
        name="api",
    ),
    re_path(
        r"^digital-download/(?P<token>[0-9A-Za-z_\-]+)/$",
        digital_product,
        name="digital-product",
    ),
    re_path(
        r"^plugins/channel/(?P<channel_slug>[.0-9A-Za-z_\-]+)/"
        r"(?P<plugin_id>[.0-9A-Za-z_\-]+)/",
        handle_plugin_per_channel_webhook,
        name="plugins-per-channel",
    ),
    re_path(
        r"^plugins/global/(?P<plugin_id>[.0-9A-Za-z_\-]+)/",
        handle_global_plugin_webhook,
        name="plugins-global",
    ),
    re_path(
        r"^plugins/(?P<plugin_id>[.0-9A-Za-z_\-]+)/",
        handle_plugin_webhook,
        name="plugins",
    ),
    re_path(
        (
            r"^thumbnail/(?P<instance_id>[.0-9A-Za-z_=\-]+)/(?P<size>\d+)/"
            r"(?:(?P<format>[a-zA-Z]+)/)?"
        ),
        handle_thumbnail,
        name="thumbnail",
    ),
    re_path(r"^\.well-known/jwks.json$", jwks, name="jwks"),
]

if settings.DEBUG:
    from .core import views

    urlpatterns += static("/media/", document_root=settings.MEDIA_ROOT) + [
        re_path(r"^static/(?P<path>.*)$", serve),
        re_path(r"^$", views.home, name="home"),
    ]

saleor/invoice/models.py
from django.conf import settings
from django.db import models
from django.db.models import JSONField
from django.utils.timezone import now

from ..app.models import App
from ..core import JobStatus
from ..core.models import Job, ModelWithMetadata
from ..core.utils import build_absolute_uri
from ..core.utils.json_serializer import CustomJsonEncoder
from ..order.models import Order
from . import InvoiceEvents


class InvoiceQueryset(models.QuerySet["Invoice"]):
    def ready(self):
        return self.filter(job__status=JobStatus.SUCCESS)


InvoiceManager = models.Manager.from_queryset(InvoiceQueryset)


class Invoice(ModelWithMetadata, Job):
    order = models.ForeignKey(
        Order,
        related_name="invoices",
        null=True,
        on_delete=models.SET_NULL,
    )
    number = models.CharField(max_length=255, null=True)
    created = models.DateTimeField(null=True)
    external_url = models.URLField(null=True, max_length=2048)
    invoice_file = models.FileField(upload_to="invoices")

    objects = InvoiceManager()

    @property
    def url(self):
        if self.invoice_file:
            return build_absolute_uri(self.invoice_file.url)
        return self.external_url

    @url.setter
    def url(self, value):
        self.external_url = value

    def update_invoice(self, number=None, url=None):
        if number is not None:
            self.number = number
        if url is not None:
            self.external_url = url

    class Meta(ModelWithMetadata.Meta):
        ordering = ("pk",)


class InvoiceEvent(models.Model):
    """Model used to store events that happened during the invoice lifecycle."""

    date = models.DateTimeField(default=now, editable=False)
    type = models.CharField(max_length=255, choices=InvoiceEvents.CHOICES)
    invoice = models.ForeignKey(
        Invoice, related_name="events", blank=True, null=True, on_delete=models.SET_NULL
    )
    order = models.ForeignKey(
        Order,
        related_name="invoice_events",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        on_delete=models.SET_NULL,
        related_name="+",
    )
    app = models.ForeignKey(App, related_name="+", on_delete=models.SET_NULL, null=True)
    parameters = JSONField(blank=True, default=dict, encoder=CustomJsonEncoder)

    class Meta:
        ordering = ("date", "pk")

    def __repr__(self):
        return f"{self.__class__.__name__}(type={self.type!r}, user={self.user!r})"

saleor/product/models.py
import copy
import datetime
from collections.abc import Iterable
from decimal import Decimal
from typing import Optional
from uuid import uuid4

import graphene
from django.conf import settings
from django.contrib.postgres.indexes import BTreeIndex, GinIndex
from django.contrib.postgres.search import SearchVectorField
from django.core.validators import MinValueValidator
from django.db import models, transaction
from django.db.models import JSONField, TextField
from django.forms.models import model_to_dict
from django.urls import reverse
from django.utils import timezone
from django_measurement.models import MeasurementField
from measurement.measures import Weight
from mptt.managers import TreeManager
from mptt.models import MPTTModel
from prices import Money

from ..channel.models import Channel
from ..core.db.fields import MoneyField, SanitizedJSONField
from ..core.models import (
    ModelWithExternalReference,
    ModelWithMetadata,
    PublishableModel,
    SortableModel,
)
from ..core.units import WeightUnits
from ..core.utils import build_absolute_uri
from ..core.utils.editorjs import clean_editor_js
from ..core.utils.translations import Translation, get_translation
from ..core.weight import zero_weight
from ..discount.models import PromotionRule
from ..permission.enums import (
    DiscountPermissions,
    OrderPermissions,
    ProductPermissions,
    ProductTypePermissions,
)
from ..seo.models import SeoModel, SeoModelTranslationWithSlug
from ..tax.models import TaxClass
from . import ProductMediaTypes, ProductTypeKind, managers

ALL_PRODUCTS_PERMISSIONS = [
    # List of permissions, where each of them allows viewing all products
    # (including unpublished).
    OrderPermissions.MANAGE_ORDERS,
    DiscountPermissions.MANAGE_DISCOUNTS,
    ProductPermissions.MANAGE_PRODUCTS,
]


class Category(ModelWithMetadata, MPTTModel, SeoModel):
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=255, unique=True, allow_unicode=True)
    description = SanitizedJSONField(blank=True, null=True, sanitizer=clean_editor_js)
    description_plaintext = TextField(blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True, null=True)
    parent = models.ForeignKey(
        "self", null=True, blank=True, related_name="children", on_delete=models.CASCADE
    )
    background_image = models.ImageField(
        upload_to="category-backgrounds", blank=True, null=True
    )
    background_image_alt = models.CharField(max_length=128, blank=True)

    objects = models.Manager()
    tree = TreeManager()  # type: ignore[django-manager-missing]

    class Meta:
        indexes = [
            *ModelWithMetadata.Meta.indexes,
            GinIndex(
                name="category_search_name_slug_gin",
                # `opclasses` and `fields` should be the same length
                fields=["name", "slug", "description_plaintext"],
                opclasses=["gin_trgm_ops"] * 3,
            ),
            BTreeIndex(fields=["updated_at"], name="updated_at_idx"),
        ]

    def __str__(self) -> str:
        return self.name


class CategoryTranslation(SeoModelTranslationWithSlug):
    category = models.ForeignKey(
        Category, related_name="translations", on_delete=models.CASCADE
    )
    name = models.CharField(max_length=128, blank=True, null=True)
    description = SanitizedJSONField(blank=True, null=True, sanitizer=clean_editor_js)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["language_code", "slug"],
                name="uniq_lang_slug_categorytransl",
            ),
        ]
        unique_together = (("language_code", "category"),)

    def __str__(self) -> str:
        return self.name if self.name else str(self.pk)

    def __repr__(self) -> str:
        class_ = type(self)
        return f"{class_.__name__}(pk={self.pk!r}, name={self.name!r}, category_pk={self.category_id!r})"

    def get_translated_object_id(self):
        return "Category", self.category_id

    def get_translated_keys(self):
        translated_keys = super().get_translated_keys()
        translated_keys.update(
            {
                "name": self.name,
                "description": self.description,
            }
        )
        return translated_keys


class ProductType(ModelWithMetadata):
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=255, unique=True, allow_unicode=True)
    kind = models.CharField(max_length=32, choices=ProductTypeKind.CHOICES)
    has_variants = models.BooleanField(default=True)
    is_shipping_required = models.BooleanField(default=True)
    is_digital = models.BooleanField(default=False)
    weight = MeasurementField(
        measurement=Weight,
        unit_choices=WeightUnits.CHOICES,
        default=zero_weight,
    )
    tax_class = models.ForeignKey(
        TaxClass,
        related_name="product_types",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )

    class Meta(ModelWithMetadata.Meta):
        ordering = ("slug",)
        app_label = "product"
        permissions = (
            (
                ProductTypePermissions.MANAGE_PRODUCT_TYPES_AND_ATTRIBUTES.codename,
                "Manage product types and attributes.",
            ),
        )
        indexes = [
            *ModelWithMetadata.Meta.indexes,
            GinIndex(
                name="product_type_search_gin",
                # `opclasses` and `fields` should be the same length
                fields=["name", "slug"],
                opclasses=["gin_trgm_ops"] * 2,
            ),
        ]

    def __str__(self) -> str:
        return self.name

    def __repr__(self) -> str:
        class_ = type(self)
        return f"<{class_.__module__}.{class_.__name__}(pk={self.pk!r}, name={self.name!r})>"


class Product(SeoModel, ModelWithMetadata, ModelWithExternalReference):
    product_type = models.ForeignKey(
        ProductType, related_name="products", on_delete=models.CASCADE
    )
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=255, unique=True, allow_unicode=True)
    description = SanitizedJSONField(blank=True, null=True, sanitizer=clean_editor_js)
    description_plaintext = TextField(blank=True)
    search_document = models.TextField(blank=True, default="")
    search_vector = SearchVectorField(blank=True, null=True)
    search_index_dirty = models.BooleanField(default=False, db_index=True)

    category = models.ForeignKey(
        Category,
        related_name="products",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField(auto_now=True, db_index=True)
    weight = MeasurementField(
        measurement=Weight,
        unit_choices=WeightUnits.CHOICES,
        blank=True,
        null=True,
    )
    default_variant = models.OneToOneField(
        "ProductVariant",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="+",
    )
    rating = models.FloatField(null=True, blank=True)
    tax_class = models.ForeignKey(
        TaxClass,
        related_name="products",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    objects = managers.ProductManager()

    class Meta:
        app_label = "product"
        ordering = ("slug",)
        permissions = (
            (ProductPermissions.MANAGE_PRODUCTS.codename, "Manage products."),
        )
        indexes = [
            GinIndex(
                name="product_search_gin",
                fields=["search_document"],
                opclasses=["gin_trgm_ops"],
            ),
            GinIndex(
                name="product_tsearch",
                fields=["search_vector"],
            ),
            GinIndex(
                name="product_gin",
                fields=["name", "slug"],
                opclasses=["gin_trgm_ops"] * 2,
            ),
            models.Index(
                fields=["category_id", "slug"],
            ),
        ]
        indexes.extend(ModelWithMetadata.Meta.indexes)

    def __iter__(self):
        if not hasattr(self, "__variants"):
            setattr(self, "__variants", self.variants.all())
        return iter(getattr(self, "__variants"))

    def __repr__(self) -> str:
        class_ = type(self)
        return f"<{class_.__module__}.{class_.__name__}(pk={self.pk!r}, name={self.name!r})>"

    def __str__(self) -> str:
        return self.name

    def get_first_image(self):
        all_media = self.media.all()
        images = [media for media in all_media if media.type == ProductMediaTypes.IMAGE]
        return images[0] if images else None

    @staticmethod
    def sort_by_attribute_fields() -> list:
        return ["concatenated_values_order", "concatenated_values", "name"]


class ProductTranslation(SeoModelTranslationWithSlug):
    product = models.ForeignKey(
        Product, related_name="translations", on_delete=models.CASCADE
    )
    name = models.CharField(max_length=250, blank=True, null=True)
    description = SanitizedJSONField(blank=True, null=True, sanitizer=clean_editor_js)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["language_code", "slug"],
                name="uniq_lang_slug_producttransl",
            ),
        ]
        unique_together = (("language_code", "product"),)

    def __str__(self) -> str:
        return self.name if self.name else str(self.pk)

    def __repr__(self) -> str:
        class_ = type(self)
        return f"{class_.__name__}(pk={self.pk!r}, name={self.name!r}, product_pk={self.product_id!r})"

    def get_translated_object_id(self):
        return "Product", self.product_id

    def get_translated_keys(self):
        translated_keys = super().get_translated_keys()
        translated_keys.update(
            {

templates/invoices/invoice.html
{% load price from taxed_prices %}
<!DOCTYPE html>
<html>

<head>
    <style>
        @page {
            margin: 0.5cm;
            @bottom-right {
                content: counter(page) " of " counter(pages);
                font-size: 12px;
                letter-spacing: 0.02em;
                color: rgba(40, 35, 74, 0.6);
                margin: -15px 28px 40px 0;
            }
        }

        @font-face {
            font-family: Custom;
            font-style: normal;
            src: url({{ font_path }}) format('truetype');
        }

        body {
            font-family: Custom;
        }

        .section-header,
        .section-invoice-info {
            background-color: #EFF5F8;
            height: 255px;
        }

        .section-left {
            width: 50%;
            float: left;
        }

        .section-right {
            width: 50%;
            float: right;
        }

        .header-category {
            font-size: 14px;
            letter-spacing: 0.05em;
            color: rgba(40, 35, 74, 0.6);
            line-height: 1.8;
        }

        .header-category-small {
            font-size: 11px;
            letter-spacing: 0.05em;
            color: rgba(40, 35, 74, 0.6);
            line-height: 1.8;
        }

        .header-item {
            font-weight: bold;
            font-size: 14px;
            color: #28234A;
            display: block;
            padding-bottom: 5px;
            font-family: Inter;
            letter-spacing: 0.05em;
            line-height: 13px;
        }

        .header-title {
            display: block;
            padding-bottom: 5px;
            font-family: Inter;
            letter-spacing: -0.02em;
            font-style: normal;
            font-weight: 600;
            font-size: 14px;
            line-height: 13px;
            color: #28234A;
        }

        .content-padded {
            padding: 27px;
        }

        .content-tight-padded {
            padding: 0 27px 0 27px;
        }

        .padded-top {
            padding-top: 30px;
        }

        .normal-text {
            font-size: 15px;
            color: #534f6e;
            line-height: 143.52%;
        }

        .normal-text-table {
            font-size: 15px;
            color: #28234A;
            line-height: 143.52%;
        }

        .summary-row {
            line-height: normal;
        }

        .padded-font {
            margin-top: 10px;
        }

        .padded-font-sm {
            margin-top: 3px;
        }

        .padded-font {
            margin-top: 1px;
        }

        .products-table {
            width: 100%;
            line-height: 1.4;
        }

        .summary-table {
            width: 100%;
            line-height: 1.8;
            padding-top: 20px;
        }

        .row-category > td,
        .row-product > td {
            padding: 7px 0 7px 0;
            border-bottom: 2px solid #CEE3ED;
        }

        .cell-product {
            width: 50%;
        }

        .cell-price {
            width: 20%;
            text-align: right;
        }

        .cell-price-content {
            padding-right: 57px;
        }

        .cell-quantity {
            width: 15%;
            text-align: right;
        }

        .cell-quantity-content {
            padding-right: 35px;
        }

        .cell-total-price {
            width: 20%;
            text-align: right;
        }

        .cell-summary {
            width: 70%;
            text-align: right;
            padding-right: 30px;
        }

        .content-separator {
            display: inline-block;
            width: 100%;
            border-bottom: 2px solid #CEE3ED;
        }

        .page-break {
            page-break-before: always;
        }
    </style>
</head>

<body>
    <div class="section-header section-left">
        <div class="content-padded">
            <span class="normal-text">{{ order.billing_address.company_name }}</span>
            <br />
            <span class="normal-text">{{ order.billing_address.street_address_1 }}</span>
            <br />
            {% if order.billing_address.street_address_2 %}
                <span class="normal-text">{{ order.billing_address.street_address_2 }}</span>
                <br />
            {% endif %}
            <span class="normal-text">{{ order.billing_address.city }}</span>
            <br />
            <span class="normal-text">{{ order.billing_address.postal_code }}</span>
            <br />
            {% if order.billing_address.phone %}
                <span class="normal-text">{{ order.billing_address.phone }}</span>
                <br />
            {% endif %}
            <span class="normal-text">{{ order.get_customer_email }}</span>
            <br />
        </div>
    </div>
    <div class="section-invoice-info section-right">
        <div class="content-padded">
            <span class="header-title">INVOICE INFORMATION</span>
            <span class="header-category">Invoice number:</span>
            <div class="padded-font-sm"></div>
            <span class="header-item">{{ invoice.number }}</span>
            <div class="padded-font"></div>
            <span class="header-category">Order:</span>
            <div class="padded-font-sm"></div>
            <span class="header-item">{{ order.number }}</span>
            <div class="padded-font"></div>
            <span class="header-category">Date:</span>
            <div class="padded-font-sm"></div>
            <span class="header-item">{{ creation_date }}</span>
            <div class="padded-font"></div>
            <span class="header-category">Amount:</span>
            <div class="padded-font-sm"></div>
            <span class="header-item">{% price order.total_gross display_gross=order.display_gross_prices %}</span>
        </div>
    </div>
    <div class="section-left">
        <div class="content-tight-padded padded-top">
            <span class="header-title">BILLING ADDRESS</span>
            <br />
            <span class="normal-text">
                {{ order.billing_address.first_name }}
                {{ order.billing_address.last_name }}
            </span>
            <br />
            <span class="normal-text">{{ order.billing_address.street_address_1 }}</span>
            <br />
            {% if order.billing_address.street_address_2 %}
                <span class="normal-text">{{ order.billing_address.street_address_2 }}</span>
                <br />
            {% endif %}
            <span class="normal-text">{{ order.billing_address.country }}</span>
            <br />
            <span class="normal-text">{{ order.billing_address.city }}</span>
            <br />
            <span class="normal-text">{{ order.billing_address.postal_code }}</span>
            <br />
            <span class="normal-text">{{ order.billing_address.phone }}</span>
            <br />
            <span class="normal-text">{{ order.get_customer_email }}</span>
            <br />
        </div>
    </div>
    <div class="section-right">
        <div class="content-tight-padded padded-top">
            <span class="header-title">SHIPMENT ADDRESS</span>
            <br />
            <span class="normal-text">
                {{ order.shipping_address.first_name }}
                {{ order.shipping_address.last_name }}
            </span>
            <br />
            <span class="normal-text">{{ order.shipping_address.street_address_1 }}</span>
            <br />
            {% if order.shipping_address.street_address_2 %}
                <span class="normal-text">{{ order.shipping_address.street_address_2 }}</span>
                <br />
            {% endif %}
            <span class="normal-text">{{ order.shipping_address.country }}</span>
            <br />
            <span class="normal-text">{{ order.shipping_address.city }}</span>
            <br />
            <span class="normal-text">{{ order.shipping_address.postal_code }}</span>
            <br />
            <span class="normal-text">{{ order.shipping_address.phone }}</span>
            <br />
            <span class="normal-text">{{ order.user_email }}</span>
            <br />
        </div>
    </div>
    <div class="content-tight-padded">
        <div class="content-separator">&nbsp;</div>
    </div>
    <div class="section-left">
        <div class="content-tight-padded padded-top">
            <span class="header-title">PAYMENT METHOD</span>
            <br />
            {% if order.get_last_payment %}
                <span class="normal-text">{{ order.get_last_payment.gateway }}</span>
            {% else %}
                <span class="normal-text">Unpaid</span>
            {% endif %}
            <br />
        </div>
    </div>
    <div class="section-right">
        <div class="content-tight-padded padded-top">
            <span class="header-title">SHIPMENT METHOD</span>
            <br />
            <span class="normal-text">{{ order.shipping_method_name }}</span>
            <br />
        </div>
    </div>
    <div class="content-tight-padded">
        <div class="content-separator">&nbsp;</div>
    </div>
    <div class="content-padded">
        <span class="header-title">ITEMS ORDERED</span>
        {% include "invoices/invoice_products_table.html" with products=products_first_page order=order %}
        {% if not rest_of_products|length %}
            {% if products_first_page|length == 4 %}
                <div class="page-break"></div>
            {% endif %}
            {% include "invoices/invoice_summary_table.html" with order=order %}
        {% else %}
            {% for product_set in rest_of_products %}
                <div class="page-break"></div>
                {% include "invoices/invoice_products_table.html" with products=product_set order=order %}
                {% if forloop.last %}
                    {% if product_set|length > 11 %}
                        <div class="page-break"></div>
                    {% endif %}
                    {% include "invoices/invoice_summary_table.html" with order=order gift_cards_payment=gift_cards_payment %}
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>
</body>

</html>

templates/invoices/invoice_products_table.html
{% load price from taxed_prices %}
<table class="products-table">
    <tbody>
        <tr class="row-category">
            <td class="cell-product">
                <span class="header-category-small">Products</span>
            </td>
            <td class="cell-price">
                <span class="header-category-small cell-price-content">Price</span>
            </td>
            <td class="cell-quantity">
                <span class="header-category-small cell-quantity-content">Quantity</span>
            </td>
            <td class="cell-total-price">
                <span class="header-category-small">Total Price</span>
            </td>
        </tr>
        {% for product in products %}
        <tr class="row-product">
            <td class="cell-product">
                <span class="normal-text-table">
                    {{ product|truncatechars:46 }}
                    {% if product.product_sku %}
                      <div class="padded-font-small"></div>
                      <span class="header-category-small">SKU: {{ product.product_sku }}</span>
                    {% endif %}
                </span>
            </td>
            <td class="cell-price">
                <span class="normal-text-table cell-price-content">{% price product.unit_price.gross display_gross=order.display_gross_prices %}</span>
            </td>
            <td class="cell-quantity">
                <span class="normal-text-table cell-quantity-content">{{ product.quantity }}</span>
            </td>
            <td class="cell-total-price">
                <span class="normal-text-table">{% price product.total_price.gross display_gross=order.display_gross_prices %}</span>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

templates/invoices/invoice_summary_table.html
{% load price from taxed_prices %}
<table class="summary-table">
    <tbody>
        <tr class="summary-row">
            <td class="cell-summary">
                <span class="normal-text-table">Subtotal</span>
            </td>
            <td class="cell-quantity"></td>
            <td class="cell-total-price">
                <span class="header-item">
                    {% price order.get_subtotal.gross display_gross=order.display_gross_prices %}
                </span>
            </td>
        </tr>
        <tr class="summary-row">
            <td class="cell-summary">
                <span class="normal-text-table">Delivery Cost</span>
            </td>
            <td class="cell-quantity"></td>
            <td class="cell-total-price">
                <span class="header-item">
                    {% price order.shipping_price.gross display_gross=order.display_gross_prices %}
                </span>
            </td>
        </tr>
        <tr class="summary-row">
            <td class="cell-summary">
                <span class="normal-text-table">Tax</span>
            </td>
            <td class="cell-quantity"></td>
            <td class="cell-total-price">
                <span class="header-item">
                    {% price order.total.tax display_gross=order.display_gross_prices %}
                </span>
            </td>
        </tr>
        {% if gift_cards_payment.amount > 0 %}
            <tr class="summary-row">
                <td class="cell-summary">
                    <span class="normal-text-table">Gift cards</span>
                </td>
                <td class="cell-quantity"></td>
                <td class="cell-total-price">
                    <span class="header-item">
                        -{% price gift_cards_payment display_gross=order.display_gross_prices %}
                    </span>
                </td>
            </tr>
        {% endif %}
        <tr class="summary-row">
            <td class="cell-summary">
                <span class="normal-text-table"><b>Grand Total</b></span>
            </td>
            <td class="cell-quantity"></td>
            <td class="cell-total-price">
                <span class="header-item">
                    {% price order.total.gross display_gross=order.display_gross_prices %}
                </span>
            </td>
        </tr>
    </tbody>
</table>